"""Type stubs for the `epanet_rs.native` submodule: idiomatic bindings for the
native epanet-rs Rust API (`Simulation`, `Network`, ...), as opposed to the
EPANET-2.3-toolkit-mirroring `epanet_rs.Project`.
"""

from __future__ import annotations

class InputError(Exception): ...
class SolverError(Exception): ...

# --- enums (mirror the corresponding Rust enums 1:1) ---

class NodeType:
    Junction: NodeType
    Reservoir: NodeType
    Tank: NodeType

class LinkType:
    Pipe: LinkType
    Pump: LinkType
    Valve: LinkType

class ValveType:
    PRV: ValveType
    PSV: ValveType
    PBV: ValveType
    FCV: ValveType
    TCV: ValveType
    PCV: ValveType
    GPV: ValveType

class LinkStatus:
    Xhead: LinkStatus
    TempClosed: LinkStatus
    Closed: LinkStatus
    Open: LinkStatus
    Active: LinkStatus
    Xflow: LinkStatus
    XFCV: LinkStatus
    XPressure: LinkStatus
    FixedOpen: LinkStatus
    FixedClosed: LinkStatus

class HeadlossFormula:
    HazenWilliams: HeadlossFormula
    DarcyWeisbach: HeadlossFormula
    ChezyManning: HeadlossFormula

class DemandModel:
    PDA: DemandModel
    DDA: DemandModel

class FlowUnits:
    CFS: FlowUnits
    GPM: FlowUnits
    MGD: FlowUnits
    IMGD: FlowUnits
    AFD: FlowUnits
    LPS: FlowUnits
    LPM: FlowUnits
    MLD: FlowUnits
    CMS: FlowUnits
    CMH: FlowUnits
    CMD: FlowUnits

class UnitSystem:
    US: UnitSystem
    SI: UnitSystem

class PressureUnits:
    PSI: PressureUnits
    KPA: PressureUnits
    METERS: PressureUnits
    FEET: PressureUnits
    BAR: PressureUnits

# --- read-only snapshot types (values are in the network's configured units) ---

class Demand:
    @property
    def basedemand(self) -> float: ...
    @property
    def pattern(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...

class Junction:
    @property
    def emitter_coefficient(self) -> float: ...
    @property
    def demands(self) -> list[Demand]: ...

class Tank:
    @property
    def elevation(self) -> float: ...
    @property
    def initial_level(self) -> float: ...
    @property
    def min_level(self) -> float: ...
    @property
    def max_level(self) -> float: ...
    @property
    def diameter(self) -> float: ...
    @property
    def min_volume(self) -> float: ...
    @property
    def volume_curve_id(self) -> str | None: ...
    @property
    def overflow(self) -> bool: ...

class Reservoir:
    @property
    def head_pattern(self) -> str | None: ...

class Node:
    @property
    def id(self) -> str: ...
    @property
    def node_type(self) -> NodeType: ...
    @property
    def elevation(self) -> float: ...
    @property
    def coordinates(self) -> tuple[float, float] | None: ...
    @property
    def junction(self) -> Junction | None: ...
    @property
    def tank(self) -> Tank | None: ...
    @property
    def reservoir(self) -> Reservoir | None: ...

class Pipe:
    @property
    def diameter(self) -> float: ...
    @property
    def length(self) -> float: ...
    @property
    def roughness(self) -> float: ...
    @property
    def minor_loss(self) -> float: ...
    @property
    def check_valve(self) -> bool: ...
    @property
    def headloss_formula(self) -> HeadlossFormula: ...

class Pump:
    @property
    def speed(self) -> float: ...
    @property
    def power(self) -> float: ...
    @property
    def head_curve_id(self) -> str | None: ...

class Valve:
    @property
    def diameter(self) -> float: ...
    @property
    def setting(self) -> float: ...
    @property
    def valve_type(self) -> ValveType: ...
    @property
    def minor_loss(self) -> float: ...
    @property
    def curve_id(self) -> str | None: ...

class Link:
    @property
    def id(self) -> str: ...
    @property
    def link_type(self) -> LinkType: ...
    @property
    def start_node_id(self) -> str: ...
    @property
    def end_node_id(self) -> str: ...
    @property
    def initial_status(self) -> LinkStatus: ...
    @property
    def vertices(self) -> list[tuple[float, float]] | None: ...
    @property
    def pipe(self) -> Pipe | None: ...
    @property
    def pump(self) -> Pump | None: ...
    @property
    def valve(self) -> Valve | None: ...

class Pattern:
    @property
    def id(self) -> str: ...
    @property
    def multipliers(self) -> list[float]: ...

class Curve:
    @property
    def id(self) -> str: ...
    @property
    def x(self) -> list[float]: ...
    @property
    def y(self) -> list[float]: ...

class ControlCondition:
    class HighPressure(ControlCondition):
        node_id: str
        target: float
    class LowPressure(ControlCondition):
        node_id: str
        target: float
    class HighLevel(ControlCondition):
        tank_id: str
        target: float
    class LowLevel(ControlCondition):
        tank_id: str
        target: float
    class Time(ControlCondition):
        seconds: int
    class ClockTime(ControlCondition):
        seconds: int

class Control:
    @property
    def link_id(self) -> str: ...
    @property
    def condition(self) -> ControlCondition: ...
    @property
    def setting(self) -> float | None: ...
    @property
    def status(self) -> LinkStatus | None: ...

# --- lazy views (see `Network.nodes`/`links`/`patterns`/`curves`/`controls`) ---
#
# Returned instead of a plain `list[...]`: `len()`/indexing touch only the
# underlying network (no snapshot construction), and `__iter__` yields one
# snapshot at a time, so partial consumption (`next(iter(...))`,
# `itertools.islice(...)`, an early `break`) does not pay for the whole
# network. Single-integer indexing (including negative indices) is
# supported; slicing is not.

class NodeView:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Node: ...
    def __iter__(self) -> NodeIter: ...

class NodeIter:
    def __iter__(self) -> NodeIter: ...
    def __next__(self) -> Node: ...

class LinkView:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Link: ...
    def __iter__(self) -> LinkIter: ...

class LinkIter:
    def __iter__(self) -> LinkIter: ...
    def __next__(self) -> Link: ...

class PatternView:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Pattern: ...
    def __iter__(self) -> PatternIter: ...

class PatternIter:
    def __iter__(self) -> PatternIter: ...
    def __next__(self) -> Pattern: ...

class CurveView:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Curve: ...
    def __iter__(self) -> CurveIter: ...

class CurveIter:
    def __iter__(self) -> CurveIter: ...
    def __next__(self) -> Curve: ...

class ControlView:
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Control: ...
    def __iter__(self) -> ControlIter: ...

class ControlIter:
    def __iter__(self) -> ControlIter: ...
    def __next__(self) -> Control: ...

# --- live id -> index maps (see `Network.node_map`/`link_map`/...) ---
#
# Unlike a plain `dict` snapshot, `__contains__`/`__getitem__`/`__len__`/
# `get` always reflect the network's *current* state. `keys()`/`values()`/
# `items()`/`__iter__` snapshot at the point they're called (matching
# Python's own `dict` iterators). Call `dict(view)` for an ordinary,
# fully-independent `dict` snapshot.

class MapKeyIter:
    def __iter__(self) -> MapKeyIter: ...
    def __next__(self) -> str: ...

class NodeMapView:
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> int: ...
    def get(self, key: str, default: int | None = None) -> int | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[int]: ...
    def items(self) -> list[tuple[str, int]]: ...
    def __iter__(self) -> MapKeyIter: ...

class LinkMapView:
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> int: ...
    def get(self, key: str, default: int | None = None) -> int | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[int]: ...
    def items(self) -> list[tuple[str, int]]: ...
    def __iter__(self) -> MapKeyIter: ...

class PatternMapView:
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> int: ...
    def get(self, key: str, default: int | None = None) -> int | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[int]: ...
    def items(self) -> list[tuple[str, int]]: ...
    def __iter__(self) -> MapKeyIter: ...

class CurveMapView:
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> int: ...
    def get(self, key: str, default: int | None = None) -> int | None: ...
    def keys(self) -> list[str]: ...
    def values(self) -> list[int]: ...
    def items(self) -> list[tuple[str, int]]: ...
    def __iter__(self) -> MapKeyIter: ...

class SolverState:
    """Snapshot of the hydraulic solver state, in the network's configured units."""

    @property
    def flows(self) -> list[float]: ...
    @property
    def heads(self) -> list[float]: ...
    @property
    def demands(self) -> list[float]: ...
    @property
    def statuses(self) -> list[LinkStatus]: ...

class SolverResult:
    """Results from a full extended-period simulation."""

    @property
    def flows(self) -> list[list[float]]: ...
    @property
    def heads(self) -> list[list[float]]: ...
    @property
    def demands(self) -> list[list[float]]: ...

class Network:
    """Pythonic wrapper around `Network::add_*`/`update_*`/`remove_*`. Obtained
    from `Simulation.network()`; shares the simulation's live network data."""

    def add_junction(
        self,
        id: str,
        elevation: float,
        basedemand: float = 0.0,
        pattern: str | None = None,
        emitter_coefficient: float = 0.0,
        coordinates: tuple[float, float] | None = None,
    ) -> None: ...
    def add_tank(
        self,
        id: str,
        elevation: float,
        initial_level: float,
        min_level: float,
        max_level: float,
        diameter: float,
        min_volume: float = 0.0,
        volume_curve_id: str | None = None,
        overflow: bool = False,
        coordinates: tuple[float, float] | None = None,
    ) -> None: ...
    def add_reservoir(
        self,
        id: str,
        elevation: float,
        head_pattern: str | None = None,
        coordinates: tuple[float, float] | None = None,
    ) -> None: ...
    def update_node(
        self, id: str, elevation: float | None = None, coordinates: tuple[float, float] | None = None
    ) -> None: ...
    def update_junction(
        self,
        id: str,
        elevation: float | None = None,
        basedemand: float | None = None,
        emitter_coefficient: float | None = None,
        clear_pattern: bool = False,
        pattern: str | None = None,
        coordinates: tuple[float, float] | None = None,
    ) -> None: ...
    def update_tank(
        self,
        id: str,
        elevation: float | None = None,
        coordinates: tuple[float, float] | None = None,
        initial_level: float | None = None,
        min_level: float | None = None,
        max_level: float | None = None,
        diameter: float | None = None,
        min_volume: float | None = None,
        overflow: bool | None = None,
    ) -> None: ...
    def update_reservoir(
        self,
        id: str,
        elevation: float | None = None,
        coordinates: tuple[float, float] | None = None,
        clear_head_pattern: bool = False,
        head_pattern: str | None = None,
    ) -> None: ...
    def remove_node(self, id: str, unconditional: bool = False) -> None: ...
    def add_pipe(
        self,
        id: str,
        start_node: str,
        end_node: str,
        length: float,
        diameter: float,
        roughness: float,
        minor_loss: float = 0.0,
        check_valve: bool = False,
        initial_status: LinkStatus = LinkStatus.Open,
        vertices: list[tuple[float, float]] | None = None,
    ) -> None: ...
    def add_pump(
        self,
        id: str,
        start_node: str,
        end_node: str,
        speed: float = 1.0,
        head_curve_id: str | None = None,
        power: float = 0.0,
        initial_status: LinkStatus = LinkStatus.Open,
        vertices: list[tuple[float, float]] | None = None,
    ) -> None: ...
    def add_valve(
        self,
        id: str,
        start_node: str,
        end_node: str,
        diameter: float,
        valve_type: ValveType,
        setting: float = 0.0,
        curve_id: str | None = None,
        minor_loss: float = 0.0,
        initial_status: LinkStatus = LinkStatus.Active,
        vertices: list[tuple[float, float]] | None = None,
    ) -> None: ...
    def update_pipe(
        self,
        id: str,
        length: float | None = None,
        diameter: float | None = None,
        roughness: float | None = None,
        minor_loss: float | None = None,
        check_valve: bool | None = None,
    ) -> None: ...
    def update_pump(
        self,
        id: str,
        speed: float | None = None,
        power: float | None = None,
        clear_head_curve: bool = False,
        head_curve_id: str | None = None,
    ) -> None: ...
    def update_valve(
        self,
        id: str,
        diameter: float | None = None,
        setting: float | None = None,
        minor_loss: float | None = None,
        clear_curve: bool = False,
        curve_id: str | None = None,
        valve_type: ValveType | None = None,
    ) -> None: ...
    def update_link(
        self,
        id: str,
        start_node: str | None = None,
        end_node: str | None = None,
        vertices: list[tuple[float, float]] | None = None,
        initial_status: LinkStatus | None = None,
    ) -> None: ...
    def remove_link(self, id: str, unconditional: bool = False) -> None: ...
    def add_pattern(self, id: str, multipliers: list[float]) -> None: ...
    def update_pattern(self, id: str, multipliers: list[float]) -> None: ...
    def remove_pattern(self, id: str) -> None: ...
    def add_curve(self, id: str, x: list[float], y: list[float]) -> None: ...
    def update_curve(self, id: str, x: list[float] | None = None, y: list[float] | None = None) -> None: ...
    def remove_curve(self, id: str) -> None: ...
    def get_node(self, id: str) -> Node: ...
    def get_link(self, id: str) -> Link: ...
    def get_pattern(self, id: str) -> Pattern: ...
    def get_curve(self, id: str) -> Curve: ...
    def nodes(self) -> NodeView: ...
    def links(self) -> LinkView: ...
    def patterns(self) -> PatternView: ...
    def curves(self) -> CurveView: ...
    def controls(self) -> ControlView: ...
    def node_map(self) -> NodeMapView: ...
    def link_map(self) -> LinkMapView: ...
    def pattern_map(self) -> PatternMapView: ...
    def curve_map(self) -> CurveMapView: ...
    def node_count(self) -> int: ...
    def link_count(self) -> int: ...
    def pattern_count(self) -> int: ...
    def curve_count(self) -> int: ...
    def title(self) -> str | None: ...
    def has_tanks(self) -> bool: ...
    def has_pressure_controls(self) -> bool: ...
    def save_network(self, path: str) -> None: ...

class Simulation:
    """Idiomatic wrapper around `epanet_rs::simulation::Simulation`."""

    @staticmethod
    def from_file(path: str) -> Simulation: ...
    @staticmethod
    def new(flow_units: FlowUnits, headloss_formula: HeadlossFormula) -> Simulation: ...
    def network(self) -> Network: ...
    def initialize_hydraulics(self) -> None: ...
    def run_hydraulics(self) -> int: ...
    def next_hydraulic_timestep(self) -> int: ...
    def solve_hydraulics(self, parallel: bool = False) -> SolverResult: ...
    @property
    def time(self) -> int: ...
    @property
    def solved(self) -> bool: ...
    def state(self) -> SolverState | None: ...
